Algoritmo "Exercicio5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Chayane Silva
// Data atual  : 31/03/2024
Var

frase: caractere
   contador, numPalavras: inteiro


Inicio

escreva ("Digite uma frase: ")
   leia(frase)

   contador <- 0
   numPalavras <- 17

   escreva ("Número de palavras na frase: ", numPalavras)


Fimalgoritmo